# Generated by Django 2.1.7 on 2019-03-20 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='janungroup',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='seminar',
            options={'ordering': ('-start_date',)},
        ),
        migrations.AlterModelOptions(
            name='seminarcomment',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('name',)},
        ),
        migrations.AlterField(
            model_name='janungroup',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='status',
            field=models.CharField(choices=[('angemeldet', 'angemeldet'), ('zurückgezogen', 'zurückgezogen'), ('zugesagt', 'zugesagt'), ('abgelehnt', 'abgelehnt'), ('abgesagt', 'abgesagt'), ('stattgefunden', 'stattgefunden'), ('ohne Abrechnung', 'ohne Abrechnung'), ('Abrechnung abgeschickt', 'Abrechnung abgeschickt'), ('Abrechnung angekommen', 'Abrechnung angekommen'), ('Abrechnung unmöglich', 'Abrechnung unmöglich'), ('rechn. Prüfung', 'rechn. Prüfung'), ('inhlt. Prüfung', 'inhlt. Prüfung'), ('Nachprüfung', 'Nachprüfung'), ('fertig geprüft', 'fertig geprüft'), ('überwiesen', 'überwiesen')], default='angemeldet', max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Teamer_in', 'Teamer_in'), ('Prüfer_in', 'Prüfer_in'), ('Verwalter_in', 'Verwalter_in')], default='Teamer_in', max_length=255),
        ),
    ]
