# Generated by Django 2.1.7 on 2019-03-21 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190320_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seminar',
            name='start_date',
            field=models.DateField(db_index=True),
        ),
    ]
