# Generated by Django 2.2.1 on 2019-05-10 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20190509_0025'),
    ]

    operations = [
        migrations.AddField(
            model_name='seminar',
            name='last_visit',
            field=models.DateTimeField(null=True),
        ),
    ]
