# Generated by Django 2.2.1 on 2019-05-30 12:28

import backend.api.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20190510_1542'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', backend.api.models.CaseInsensitiveUserManager()),
            ],
        ),
    ]
