# Generated by Django 2.2.2 on 2019-06-10 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20190530_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='janungroup',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
