# Generated by Django 2.2.2 on 2019-06-10 14:47

from django.db import migrations
from django.utils.text import slugify


def fill_in_slugs(apps, schema_editor):
    JANUNGroup = apps.get_model("api", "JANUNGroup")
    for group in JANUNGroup.objects.all():
        group.slug = slugify(group.name)
        group.save()


class Migration(migrations.Migration):

    dependencies = [("api", "0012_janungroup_slug")]

    operations = [migrations.RunPython(fill_in_slugs)]
