# Generated by Django 2.2.2 on 2019-06-10 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20190610_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='janungroup',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
