# Generated by Django 2.2.2 on 2019-06-11 13:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20190610_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='seminar',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
