# Generated by Django 2.2.2 on 2019-06-11 13:30
import uuid
from django.db import migrations


def create_uuid(apps, schema_editor):
    Seminar = apps.get_model("api", "Seminar")
    for seminar in Seminar.objects.all():
        seminar.uuid = uuid.uuid4()
        seminar.save()


class Migration(migrations.Migration):

    dependencies = [("api", "0015_seminar_uuid")]

    operations = [migrations.RunPython(create_uuid)]
