# Generated by Django 2.2.2 on 2019-06-11 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20190611_1530'),
    ]

    operations = [
    ]
