# Generated by Django 2.2.2 on 2019-06-15 14:32

import uuid
from django.db import migrations


def create_uuid(apps, schema_editor):
    SeminarComment = apps.get_model("api", "SeminarComment")
    for comment in SeminarComment.objects.all():
        comment.uuid = uuid.uuid4()
        comment.save()


class Migration(migrations.Migration):

    dependencies = [("api", "0018_auto_20190615_1631")]

    operations = [migrations.RunPython(create_uuid)]
