# Generated by Django 2.2.2 on 2019-06-15 14:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20190615_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seminarcomment',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
