# Generated by Django 2.2.6 on 2019-10-19 13:47

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_auto_20190929_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='janungroup',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, max_length=100, null=True, populate_from='name', unique=True, verbose_name='URL-Titel'),
        ),
    ]
