# Generated by Django 2.2.7 on 2019-11-17 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0005_historicaljanungroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaljanungroup',
            name='history_change_reason',
            field=models.TextField(null=True),
        ),
    ]
