# Generated by Django 2.0.4 on 2018-07-03 14:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_fsm


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Seminar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Titel')),
                ('start', models.DateTimeField(verbose_name='Startzeit')),
                ('end', models.DateTimeField(verbose_name='Endzeit')),
                ('state', django_fsm.FSMField(choices=[('ANGEMELDET', 'Seminar angemeldet'), ('ZURUECKGEZOGEN', 'Antrag zurückgezogen'), ('ZUGESAGT', 'Förderung zugesagt'), ('ABGELEHNT', 'Förderung abgelehnt'), ('ABGESAGT', 'Seminar abgesagt'), ('STATTGEFUNDEN', 'Seminar hat stattgefunden'), ('OHNE_ABRECHNUNG', 'ohne Abrechnung'), ('ABGESCHICKT', 'Abrechnung abgeschickt'), ('ANGEKOMMEN', 'Abrechnung angekommen'), ('UNMOEGLICH', 'Abrechnung unmöglich'), ('RECHNERISCH', 'rechnerische Prüfung'), ('INHALTLICH', 'inhaltliche Prüfung'), ('NACHPRUEFUNG', 'Nachprüfung'), ('FERTIG', 'fertig geprüft'), ('UEBERWIESEN', 'überwiesen')], default='angemeldet', max_length=50, verbose_name='Status')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seminars', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seminars', to='groups.JANUNGroup', verbose_name='Gruppe')),
            ],
            options={
                'verbose_name': 'Seminar',
                'verbose_name_plural': 'Seminare',
                'ordering': ['start'],
            },
        ),
    ]
