# Generated by Django 2.0.4 on 2018-07-09 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seminars', '0002_auto_20180704_1333'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seminar',
            options={'ordering': ['start'], 'permissions': (('detail_seminars', 'Kann Seminardaten sehen'), ('can_see_all_seminars', 'Kann alle Seminare sehen')), 'verbose_name': 'Seminar', 'verbose_name_plural': 'Seminare'},
        ),
    ]
