# Generated by Django 2.0.4 on 2018-07-24 12:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('seminars', '0003_auto_20180709_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='seminar',
            name='content',
            field=models.TextField(blank=True, help_text='Welche Inhalte werden in Deinem Seminar vermittelt?', null=True, verbose_name='Inhalt'),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seminars', to=settings.AUTH_USER_MODEL, verbose_name='Autor_in'),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='state',
            field=django_fsm.FSMField(choices=[('ANGEMELDET', 'angemeldet'), ('ZURUECKGEZOGEN', 'zurückgezogen'), ('ZUGESAGT', 'zugesagt'), ('ABGELEHNT', 'abgelehnt'), ('ABGESAGT', 'abgesagt'), ('STATTGEFUNDEN', 'hat stattgefunden'), ('OHNE_ABRECHNUNG', 'ohne Abrechnung'), ('ABGESCHICKT', 'Abrechnung abgeschickt'), ('ANGEKOMMEN', 'Abrechnung angekommen'), ('UNMOEGLICH', 'Abrechnung unmöglich'), ('RECHNERISCH', 'rechn. Prüfung'), ('INHALTLICH', 'inhlt. Prüfung'), ('NACHPRUEFUNG', 'Nachprüfung'), ('FERTIG', 'fertig geprüft'), ('UEBERWIESEN', 'überwiesen')], default='angemeldet', max_length=50, verbose_name='Status'),
        ),
    ]
