# Generated by Django 2.0.4 on 2018-07-24 13:11

import django.contrib.postgres.fields.ranges
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminars', '0004_auto_20180724_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='seminar',
            name='attendees',
            field=django.contrib.postgres.fields.ranges.IntegerRangeField(default=(1,1), verbose_name='Anzahl Teilnehmer_innen'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seminar',
            name='location',
            field=models.CharField(default="Hannover", max_length=255, verbose_name='Ort'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seminar',
            name='training_days',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Anzahl Bildungstage'),
            preserve_default=False,
        ),
    ]
