# Generated by Django 2.0.4 on 2018-07-24 13:27

import django.contrib.postgres.fields.ranges
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminars', '0005_auto_20180724_1511'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seminar',
            old_name='training_days',
            new_name='planned_training_days',
        ),
        migrations.RemoveField(
            model_name='seminar',
            name='attendees',
        ),
        migrations.AddField(
            model_name='seminar',
            name='planned_attendees',
            field=django.contrib.postgres.fields.ranges.IntegerRangeField(default=(1, 1), verbose_name='Anzahl Teilnehmende'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seminar',
            name='requested_funding',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
            preserve_default=False,
        ),
    ]
