# Generated by Django 2.0.4 on 2018-08-04 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminars', '0006_auto_20180724_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='seminar',
            name='hearing_barriers',
            field=models.TextField(blank=True, help_text='Zum Bsp.: Werden Filme mit oder ohne Untertitel gezeigt?Sind laute (Stör-)Geräusche wahrscheinlich?', null=True, verbose_name='Hör-Barrieren'),
        ),
        migrations.AddField(
            model_name='seminar',
            name='language_barriers',
            field=models.TextField(blank=True, help_text='Zum Bsp.: Kommen viele Fachausdrücke vor?Sind die Workshops auch für Menschen geeignet, die wenig Deutsch sprechen?', null=True, verbose_name='Sprach-Barrieren'),
        ),
        migrations.AddField(
            model_name='seminar',
            name='mobility_barriers',
            field=models.TextField(blank=True, help_text='Zum Bsp.: Müssen Stufen oder Treppen überwunden werden?Findet ein Workshop im Garten statt? Sind sportliche Betätigungen vorgesehen?', null=True, verbose_name='Moblitäts-Barrieren'),
        ),
        migrations.AddField(
            model_name='seminar',
            name='seeing_barriers',
            field=models.TextField(blank=True, help_text='Zum Bsp.: Findet Textarbeit statt? Muss man Farben erkennen können?', null=True, verbose_name='Seh-Barrieren'),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='content',
            field=models.TextField(default='', help_text='Welche Inhalte werden in Deinem Seminar vermittelt?', verbose_name='Inhalt'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='seminar',
            name='requested_funding',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Benötigte Förderung'),
        ),
    ]
