# Generated by Django 2.0.4 on 2018-08-07 21:21

from django.db import migrations, models
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('seminars', '0007_auto_20180804_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seminar',
            name='state',
            field=django_fsm.FSMField(choices=[('ANGEMELDET', 'angemeldet'), ('ZURUECKGEZOGEN', 'zurückgezogen'), ('ZUGESAGT', 'zugesagt'), ('ABGELEHNT', 'abgelehnt'), ('ABGESAGT', 'abgesagt'), ('STATTGEFUNDEN', 'hat stattgefunden'), ('OHNE_ABRECHNUNG', 'ohne Abrechnung'), ('ABGESCHICKT', 'Abrechnung abgeschickt'), ('ANGEKOMMEN', 'Abrechnung angekommen'), ('UNMOEGLICH', 'Abrechnung unmöglich'), ('RECHNERISCH', 'rechn. Prüfung'), ('INHALTLICH', 'inhlt. Prüfung'), ('NACHPRUEFUNG', 'Nachprüfung'), ('FERTIG', 'fertig geprüft'), ('UEBERWIESEN', 'überwiesen')], default='ANGEMELDET', max_length=50, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='title',
            field=models.CharField(max_length=255, unique_for_date='start', verbose_name='Titel'),
        ),
    ]
