# Generated by Django 2.1.1 on 2018-09-28 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminars', '0009_seminarcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seminarcomment',
            name='comment',
            field=models.TextField(verbose_name='Kommentartext'),
        ),
    ]
