# Generated by Django 2.1.1 on 2018-10-15 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminars', '0010_auto_20180928_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seminar',
            name='content',
            field=models.TextField(help_text='Um was genau geht es in Deinem Seminar?<br>Welche Inhalte werden in Deinem Seminar vermittelt?', verbose_name='Inhalt'),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='end',
            field=models.DateTimeField(verbose_name='Ende'),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='start',
            field=models.DateTimeField(verbose_name='Anfang'),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='title',
            field=models.CharField(help_text='Beschreib oder bennene Dein Seminar in wenigen Worten', max_length=255, unique_for_date='start', verbose_name='Titel'),
        ),
    ]
