# Generated by Django 2.1.1 on 2018-10-15 13:10

from django.db import migrations


def set_dates_and_times(apps, schema_editor):
    Seminar = apps.get_model('seminars', 'Seminar')
    for seminar in Seminar.objects.all().iterator():
        seminar.start_date = seminar.start.date()
        seminar.start_time = seminar.start.time()
        seminar.end_date = seminar.end.date()
        seminar.end_time = seminar.end.time()
        seminar.save()


class Migration(migrations.Migration):

    dependencies = [
        ('seminars', '0012_auto_20181015_1458'),
    ]

    operations = [
        migrations.RunPython(set_dates_and_times),
    ]
