# Generated by Django 2.1.1 on 2018-10-15 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seminars', '0013_auto_20181015_1510'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seminar',
            name='end',
        ),
        migrations.RemoveField(
            model_name='seminar',
            name='start',
        ),
    ]
