# Generated by Django 2.1.1 on 2018-10-18 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminars', '0014_auto_20181015_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seminar',
            name='end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Endzeit'),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Anfangszeit'),
        ),
    ]
