# Generated by Django 2.1.1 on 2018-10-19 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminars', '0015_auto_20181018_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seminar',
            name='hearing_barriers',
            field=models.TextField(blank=True, help_text='Zum Bsp.: Werden Filme mit oder ohne Untertitel gezeigt? Sind laute (Stör-)Geräusche wahrscheinlich?', null=True, verbose_name='Hör-Barrieren'),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='language_barriers',
            field=models.TextField(blank=True, help_text='Zum Bsp.: Kommen viele Fachausdrücke vor? Sind die Workshops auch für Menschen geeignet, die wenig Deutsch sprechen?', null=True, verbose_name='Sprach-Barrieren'),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='mobility_barriers',
            field=models.TextField(blank=True, help_text='Zum Bsp.: Müssen Stufen oder Treppen überwunden werden? Findet ein Workshop im Garten statt? Sind sportliche Betätigungen vorgesehen?', null=True, verbose_name='Moblitäts-Barrieren'),
        ),
    ]
