# Generated by Django 2.1.1 on 2018-10-26 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seminars', '0018_auto_20181026_1555'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seminar',
            name='planned_attendees',
        ),
    ]
