# Generated by Django 2.1.1 on 2018-12-07 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminars', '0019_remove_seminar_planned_attendees'),
    ]

    operations = [
        migrations.AddField(
            model_name='seminarcomment',
            name='is_internal',
            field=models.BooleanField(default=False, help_text='Kann nur von Prüfern und Verwaltern gelesen werden', verbose_name='interner Vermerk'),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='location',
            field=models.CharField(help_text='Stadt, in der das Seminar stattfinden soll.', max_length=255, verbose_name='Ort'),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='mobility_barriers',
            field=models.TextField(blank=True, help_text='Zum Bsp.: Müssen Stufen oder Treppen überwunden werden? Findet ein Workshop im Garten statt? Sind sportliche Betätigungen vorgesehen?', null=True, verbose_name='Mobilitäts-Barrieren'),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='title',
            field=models.CharField(help_text='Beschreibe oder bennene Dein Seminar in wenigen Worten', max_length=255, unique_for_date='start_date', verbose_name='Titel'),
        ),
    ]
