# Generated by Django 2.1.5 on 2019-01-14 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminars', '0020_auto_20181207_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='seminar',
            name='ausgaben_fahrtkosten',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Fahrtkosten'),
        ),
        migrations.AddField(
            model_name='seminar',
            name='ausgaben_referenten',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Referent_innen'),
        ),
        migrations.AddField(
            model_name='seminar',
            name='ausgaben_sonstiges',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Sonstiges'),
        ),
        migrations.AddField(
            model_name='seminar',
            name='ausgaben_unterkunft',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Unterkunft'),
        ),
        migrations.AddField(
            model_name='seminar',
            name='ausgaben_verpflegung',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Verpflegung'),
        ),
        migrations.AddField(
            model_name='seminar',
            name='einnahmen_beitraege',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='TN-Beiträge'),
        ),
        migrations.AddField(
            model_name='seminar',
            name='einnahmen_oeffentlich',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Öffentl. Zuwendungen'),
        ),
        migrations.AddField(
            model_name='seminar',
            name='einnahmen_sonstiges',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Sonstiges'),
        ),
        migrations.AddField(
            model_name='seminar',
            name='tn_jfg',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='TN nach JFG'),
        ),
        migrations.AddField(
            model_name='seminar',
            name='tn_total',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='TN insgesamt'),
        ),
        migrations.AddField(
            model_name='seminar',
            name='tnt_jfg',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='TNT nach JFG'),
        ),
        migrations.AddField(
            model_name='seminar',
            name='tnt_total',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='TNT nach Richtlinie'),
        ),
        migrations.AddField(
            model_name='seminar',
            name='verwendungsnachweis',
            field=models.BooleanField(default=True, help_text='Soll das Seminar im Verwendungsnachweis auftauchen?', verbose_name='Verwendungsnachweis'),
        ),
        migrations.AddField(
            model_name='seminar',
            name='vorschuss',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Vorschuss'),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='content',
            field=models.TextField(help_text='Um was genau geht es in dem Seminar?<br>Welche Inhalte werden vermittelt?', verbose_name='Inhalt'),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='title',
            field=models.CharField(help_text='Beschreibe oder benenne das Seminar in wenigen Worten', max_length=255, verbose_name='Titel'),
        ),
        migrations.AlterField(
            model_name='seminarcomment',
            name='is_internal',
            field=models.BooleanField(default=False, help_text='Sehen nur Prüfer und Verwalter', verbose_name='interner Vermerk'),
        ),
    ]
