# Generated by Django 2.1.5 on 2019-01-15 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminars', '0021_auto_20190115_0015'),
    ]

    operations = [
        migrations.AddField(
            model_name='seminar',
            name='training_days',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Bildungstage'),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='einnahmen_oeffentlich',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Öffentlich'),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='tnt_jfg',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='nach JFG'),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='tnt_total',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='nach Richtlinie'),
        ),
    ]
