# Generated by Django 2.1.5 on 2019-01-16 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminars', '0023_seminar_landkreise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seminar',
            name='landkreise',
            field=models.CharField(blank=True, choices=[('1', '1 Landkreis'), ('2', '2–3 Landkreisen'), ('4', '4 oder mehr Landkreisen')], help_text='Alle Teilnehmenden kommen aus…', max_length=100, verbose_name='TN-Landkreise'),
        ),
    ]
