# Generated by Django 2.1.5 on 2019-01-19 13:18

from django.db import migrations


def set_none_fields_to_zero(apps, schema_editor):
    Seminar = apps.get_model('seminars', 'Seminar')
    fields = (
        'ausgaben_fahrtkosten',
        'ausgaben_referenten',
        'ausgaben_sonstiges',
        'ausgaben_unterkunft',
        'ausgaben_verpflegung',
        'einnahmen_beitraege',
        'einnahmen_oeffentlich',
        'einnahmen_sonstiges',
        'vorschuss',
    )
    for seminar in Seminar.objects.all():
        for field in fields:
            value = getattr(seminar, field)
            if value is None:
                setattr(seminar, field, 0)
        seminar.save()


class Migration(migrations.Migration):

    dependencies = [
        ('seminars', '0024_auto_20190116_1837'),
    ]

    operations = [
        migrations.RunPython(set_none_fields_to_zero)
    ]
