# Generated by Django 2.1.5 on 2019-01-19 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminars', '0025_auto_20190119_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seminar',
            name='ausgaben_fahrtkosten',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Fahrtkosten'),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='ausgaben_referenten',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Referent_innen'),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='ausgaben_sonstiges',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Sonstiges'),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='ausgaben_unterkunft',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Unterkunft'),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='ausgaben_verpflegung',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Verpflegung'),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='einnahmen_beitraege',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='TN-Beiträge'),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='einnahmen_oeffentlich',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Öff. Zuwendungen'),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='einnahmen_sonstiges',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='Sonstiges'),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='vorschuss',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Vorschuss'),
        ),
    ]
