# Generated by Django 2.1.5 on 2019-01-24 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminars', '0026_auto_20190119_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='seminar',
            name='foerderbedarf',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Förderbedarf'),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='einnahmen_oeffentlich',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Öff. Zuwendg.'),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='landkreise',
            field=models.CharField(blank=True, choices=[('1', '1 Landkreis'), ('2', '2–3 Landkreisen'), ('4', '4 oder mehr Landkreisen')], max_length=100, verbose_name='TN-Landkreise'),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='planned_training_days',
            field=models.PositiveSmallIntegerField(verbose_name='gepl. Bildungstage'),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='tnt_jfg',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='TNT nach JFG'),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='tnt_total',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='TNT nach RL'),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='training_days',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='tats. Bildungstage'),
        ),
    ]
