# Generated by Django 2.2.10 on 2020-03-05 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplate',
            name='cc_template',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='CC-Kopie'),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='from_template',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Absender'),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='to_template',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Empfänger'),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='subject_template',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Betreff'),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='template_key',
            field=models.CharField(choices=[('seminar_applied', 'Seminar angemeldet')], help_text='Wann diese E-Mail verschickt werden soll', max_length=255, verbose_name='Bedingung'),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='text_template',
            field=models.TextField(blank=True, null=True, verbose_name='Text'),
        ),
    ]
