# Generated by Django 2.2.10 on 2020-03-05 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0003_auto_20200305_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='cc_template',
            field=models.CharField(blank=True, help_text='Mehrere durch Komma trennen', max_length=255, null=True, verbose_name='CC-Kopie'),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='from_template',
            field=models.CharField(default='seminare@janun.de', max_length=255, verbose_name='Absender'),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='to_template',
            field=models.CharField(default='{{ user.email }}', help_text='Mehrere durch Komma trennen', max_length=255, verbose_name='Empfänger'),
        ),
    ]
