# Generated by Django 2.2.11 on 2020-03-11 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0006_auto_20200311_0123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='template_key',
            field=models.CharField(choices=[('seminar_applied', 'Seminar angemeldet'), ('seminar_delete', 'Seminar gelöscht'), ('seminar_update', 'Seminar geändert'), ('seminar_deadline_expired', 'Seminar Abrechnungsfrist abgelaufen'), ('user_signup', 'Benutzer registriert')], help_text='Wann diese E-Mail verschickt werden soll', max_length=255, verbose_name='Grundbedingung'),
        ),
    ]
