# Generated by Django 2.2.4 on 2019-09-05 15:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seminar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('angemeldet', 'angemeldet'), ('zurückgezogen', 'zurückgezogen'), ('zugesagt', 'zugesagt'), ('abgelehnt', 'abgelehnt'), ('abgesagt', 'abgesagt'), ('stattgefunden', 'stattgefunden'), ('ohne Abrechnung', 'ohne Abrechnung'), ('Abrechnung abgeschickt', 'Abrechnung abgeschickt'), ('Abrechnung angekommen', 'Abrechnung angekommen'), ('Abrechnung unmöglich', 'Abrechnung unmöglich'), ('rechnerische Prüfung', 'rechnerische Prüfung'), ('inhaltliche Prüfung', 'inhaltliche Prüfung'), ('Zweitprüfung', 'Zweitprüfung'), ('fertig geprüft', 'fertig geprüft'), ('überwiesen', 'überwiesen')], default='angemeldet', max_length=255)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateField(db_index=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_date', models.DateField()),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('planned_training_days', models.PositiveSmallIntegerField()),
                ('planned_attendees_min', models.PositiveSmallIntegerField()),
                ('planned_attendees_max', models.PositiveSmallIntegerField()),
                ('requested_funding', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-start_date',),
            },
        ),
        migrations.CreateModel(
            name='SeminarComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
