# Generated by Django 2.2.4 on 2019-09-07 14:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seminars', '0002_auto_20190905_1731'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seminar',
            options={'ordering': ('-start_date',), 'verbose_name': 'Seminar', 'verbose_name_plural': 'Seminare'},
        ),
        migrations.AlterModelOptions(
            name='seminarcomment',
            options={'ordering': ('-created_at',), 'verbose_name': 'Kommentar', 'verbose_name_plural': 'Kommentare'},
        ),
        migrations.AddField(
            model_name='seminar',
            name='advance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Vorschuss'),
        ),
        migrations.AddField(
            model_name='seminar',
            name='attendees_jfg',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='TN nach JFG'),
        ),
        migrations.AddField(
            model_name='seminar',
            name='attendees_total',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='TN insgesamt'),
        ),
        migrations.AddField(
            model_name='seminar',
            name='attendence_days_jfg',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='TNT nach JFG'),
        ),
        migrations.AddField(
            model_name='seminar',
            name='attendence_days_total',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='TNT insgesamt'),
        ),
        migrations.AddField(
            model_name='seminar',
            name='foerderbedarf',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Förderbedarf'),
        ),
        migrations.AddField(
            model_name='seminar',
            name='training_days',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Bildungstage'),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am'),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='description',
            field=models.TextField(blank=True, verbose_name='Beschreibung'),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='end_date',
            field=models.DateField(verbose_name='End-Datum'),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='End-Zeit'),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seminars', to='groups.JANUNGroup', verbose_name='JANUN-Gruppe'),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='location',
            field=models.CharField(blank=True, max_length=255, verbose_name='Ort'),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seminars', to=settings.AUTH_USER_MODEL, verbose_name='Eigentümer'),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='planned_attendees_max',
            field=models.PositiveSmallIntegerField(verbose_name='geplante TN max.'),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='planned_attendees_min',
            field=models.PositiveSmallIntegerField(verbose_name='geplante TN min.'),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='planned_training_days',
            field=models.PositiveSmallIntegerField(verbose_name='geplante Bildungstage'),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='requested_funding',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='angeforderte Förderung'),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='start_date',
            field=models.DateField(db_index=True, verbose_name='Start-Datum'),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Start-Zeit'),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='status',
            field=models.CharField(choices=[('angemeldet', 'angemeldet'), ('zurückgezogen', 'zurückgezogen'), ('zugesagt', 'zugesagt'), ('abgelehnt', 'abgelehnt'), ('abgesagt', 'abgesagt'), ('stattgefunden', 'stattgefunden'), ('ohne Abrechnung', 'ohne Abrechnung'), ('Abrechnung abgeschickt', 'Abrechnung abgeschickt'), ('Abrechnung angekommen', 'Abrechnung angekommen'), ('Abrechnung unmöglich', 'Abrechnung unmöglich'), ('rechnerische Prüfung', 'rechnerische Prüfung'), ('inhaltliche Prüfung', 'inhaltliche Prüfung'), ('Zweitprüfung', 'Zweitprüfung'), ('fertig geprüft', 'fertig geprüft'), ('überwiesen', 'überwiesen')], default='angemeldet', max_length=255, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Titel'),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Geändert am'),
        ),
        migrations.AlterField(
            model_name='seminarcomment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am'),
        ),
        migrations.AlterField(
            model_name='seminarcomment',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='Autor'),
        ),
        migrations.AlterField(
            model_name='seminarcomment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Geändert am'),
        ),
        migrations.CreateModel(
            name='FinanceRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Betrag')),
                ('name', models.CharField(max_length=255, verbose_name='Bezeichnung')),
                ('seminar', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_records', to='seminars.Seminar')),
            ],
            options={
                'verbose_name': 'Einnahme/Ausgabe',
                'verbose_name_plural': 'Einnahmen/Ausgaben',
                'ordering': ('name',),
            },
        ),
    ]
