# Generated by Django 2.2.4 on 2019-09-07 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seminars', '0003_auto_20190907_1612'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seminar',
            old_name='foerderbedarf',
            new_name='funding',
        ),
    ]
