# Generated by Django 2.2.4 on 2019-09-07 14:30

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminars', '0004_auto_20190907_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='financerecord',
            name='income',
            field=models.BooleanField(default=False, verbose_name='Einnahme?'),
        ),
        migrations.AlterField(
            model_name='financerecord',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Betrag'),
        ),
    ]
