# Generated by Django 2.2.4 on 2019-09-07 14:40

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seminars', '0005_auto_20190907_1630'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeminarExpenseRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Betrag')),
                ('name', models.CharField(max_length=255, verbose_name='Bezeichnung')),
                ('seminar', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='seminars.Seminar')),
            ],
            options={
                'verbose_name': 'Ausgabe',
                'verbose_name_plural': 'Ausgaben',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='SeminarIncomeRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Betrag')),
                ('name', models.CharField(max_length=255, verbose_name='Bezeichnung')),
                ('seminar', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incomes', to='seminars.Seminar')),
            ],
            options={
                'verbose_name': 'Einnahme',
                'verbose_name_plural': 'Einnahmen',
                'ordering': ('name',),
            },
        ),
        migrations.DeleteModel(
            name='FinanceRecord',
        ),
    ]
