# Generated by Django 2.2.4 on 2019-09-08 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminars', '0006_auto_20190907_1640'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seminarincomerecord',
            name='seminar',
        ),
        migrations.AddField(
            model_name='seminar',
            name='expense_accomodation',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Ausgaben für Unterkunft'),
        ),
        migrations.AddField(
            model_name='seminar',
            name='expense_catering',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Ausgaben für Verpflegung'),
        ),
        migrations.AddField(
            model_name='seminar',
            name='expense_other',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Sonstige Ausgaben'),
        ),
        migrations.AddField(
            model_name='seminar',
            name='expense_referent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Ausgaben für Referent_innen'),
        ),
        migrations.AddField(
            model_name='seminar',
            name='expense_travel',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Fahrtkosten'),
        ),
        migrations.AddField(
            model_name='seminar',
            name='income_fees',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Teilnahmebeiträge'),
        ),
        migrations.AddField(
            model_name='seminar',
            name='income_other',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Sonstige Einnahmen'),
        ),
        migrations.AddField(
            model_name='seminar',
            name='income_public',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Öffentliche Zuwendungen'),
        ),
        migrations.DeleteModel(
            name='SeminarExpenseRecord',
        ),
        migrations.DeleteModel(
            name='SeminarIncomeRecord',
        ),
    ]
