# Generated by Django 2.2.5 on 2019-09-11 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminars', '0012_auto_20190911_1428'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seminar',
            name='uuid',
        ),
        migrations.RemoveField(
            model_name='seminarcomment',
            name='uuid',
        ),
        migrations.AddField(
            model_name='seminarcomment',
            name='is_internal',
            field=models.BooleanField(default=False, verbose_name='intern?'),
        ),
    ]
