# Generated by Django 2.2.5 on 2019-09-13 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminars', '0013_auto_20190911_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='seminar',
            name='transferred_at',
            field=models.DateField(blank=True, null=True, verbose_name='überwiesen am'),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='deadline',
            field=models.DateField(help_text='Aus End-Datum errechnet', verbose_name='Abrechnungsdeadline'),
        ),
    ]
