# Generated by Django 2.2.5 on 2019-09-15 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminars', '0017_remove_seminar_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='seminar',
            name='slug',
            field=models.SlugField(null=True, unique=True, verbose_name='URL-Titel'),
        ),
    ]
