# Generated by Django 2.2.5 on 2019-09-15 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminars', '0018_seminar_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seminar',
            name='slug',
            field=models.SlugField(max_length=100, null=True, unique=True, verbose_name='URL-Titel'),
        ),
    ]
