# Generated by Django 2.2.5 on 2019-09-15 18:36

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('seminars', '0019_auto_20190915_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seminar',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, max_length=100, null=True, populate_from='title', unique=True, verbose_name='URL-Titel'),
        ),
    ]
