# Generated by Django 2.2.5 on 2019-09-15 18:37

from django.db import migrations


def fill_slug(apps, schema_editor):
    Seminar = apps.get_model("seminars", "Seminar")
    for seminar in Seminar.objects.all():
        seminar.save()


class Migration(migrations.Migration):

    dependencies = [("seminars", "0020_auto_20190915_2036")]

    operations = [migrations.RunPython(fill_slug)]
