# Generated by Django 2.2.5 on 2019-09-29 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminars', '0021_auto_20190915_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seminar',
            name='location',
            field=models.CharField(blank=True, help_text='Stadt, in der das Seminar stattfindet', max_length=255, verbose_name='Ort'),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='planned_attendees_max',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='geplante Teilnehmende max.'),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='planned_attendees_min',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='geplante Teilnehmende min.'),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='requested_funding',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='gewünschte Förderung'),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='status',
            field=models.CharField(choices=[('angemeldet', 'angemeldet'), ('zugesagt', 'zugesagt'), ('stattgefunden', 'stattgefunden'), ('Abrechnung abgeschickt', 'Abrechnung abgeschickt'), ('Abrechnung angekommen', 'Abrechnung angekommen'), ('rechnerische Prüfung', 'rechnerische Prüfung'), ('inhaltliche Prüfung', 'inhaltliche Prüfung'), ('Zweitprüfung', 'Zweitprüfung'), ('fertig geprüft', 'fertig geprüft'), ('überwiesen', 'überwiesen'), ('abgelehnt', 'abgelehnt'), ('abgesagt', 'abgesagt'), ('ohne Abrechnung', 'ohne Abrechnung'), ('Abrechnung unmöglich', 'Abrechnung unmöglich')], default='angemeldet', max_length=255, verbose_name='Status'),
        ),
    ]
