# Generated by Django 2.2.6 on 2019-10-06 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminars', '0022_auto_20190929_1531'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundingRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Jahr')),
                ('group_rate', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Satz für Gruppen')),
                ('single_rate', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Satz für Einzelpersonen')),
                ('group_rate_one_day', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Satz für Gruppen für Eintagesseminare')),
                ('single_rate_one_day', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Satz für Einzelpersonen für Eintagesseminare')),
                ('group_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Gruppen-Limit')),
                ('single_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Einzelpersonen-Limit')),
                ('group_limit_formula', models.CharField(help_text='engl. Excel-Formel, z.B. =IF(B>=3,(B-3)*200+450,450)', max_length=255, verbose_name='Formel für Gruppen-Limit')),
                ('single_limit_formula', models.CharField(help_text='engl. Excel-Formel, z.B. =IF(B>=3,(B-3)*200+450,450)', max_length=255, verbose_name='Formel für Einzelpersonen-Limit')),
            ],
            options={
                'verbose_name': 'Förderungssatz',
                'verbose_name_plural': 'Förderungssätze',
            },
        ),
    ]
