# Generated by Django 2.2.6 on 2019-10-06 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seminars', '0023_fundingrate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Limit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.IntegerField(verbose_name='Anzahl Bildungstage')),
                ('limit', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Obergrenze')),
            ],
            options={
                'verbose_name': 'Obergrenze',
                'verbose_name_plural': 'Obergrenzen',
            },
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.IntegerField(verbose_name='Anzahl Bildungstage')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Förderungssatz')),
            ],
            options={
                'verbose_name': 'Förderungssatz',
                'verbose_name_plural': 'Förderungssätze',
            },
        ),
        migrations.CreateModel(
            name='YearFundingRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Jahr')),
            ],
            options={
                'verbose_name': 'Jährlicher Förderungssatz',
                'verbose_name_plural': 'Jährliche Förderungssätze',
            },
        ),
        migrations.DeleteModel(
            name='FundingRate',
        ),
        migrations.AddField(
            model_name='rate',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='seminars.YearFundingRate', verbose_name='Jahr'),
        ),
        migrations.AddField(
            model_name='limit',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='limits', to='seminars.YearFundingRate', verbose_name='Jahr'),
        ),
    ]
