# Generated by Django 2.2.6 on 2019-10-15 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminars', '0025_auto_20191006_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundingrate',
            name='group_limit',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Hat Vorrang vor der Formel', max_digits=10, null=True, verbose_name='Gruppen-Limit'),
        ),
        migrations.AlterField(
            model_name='fundingrate',
            name='single_limit',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Hat Vorrang vor der Formel', max_digits=10, null=True, verbose_name='Einzelpersonen-Limit'),
        ),
    ]
