# Generated by Django 2.2.6 on 2019-10-24 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminars', '0026_auto_20191015_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seminar',
            name='description',
            field=models.TextField(blank=True, help_text='Um was genau geht es in dem Seminar? Welche Inhalte werden vermittelt?', verbose_name='Beschreibung'),
        ),
    ]
