# Generated by Django 2.2.6 on 2019-10-29 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminars', '0027_auto_20191024_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundingrate',
            name='year',
            field=models.IntegerField(unique=True, verbose_name='Jahr'),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='title',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Titel'),
        ),
    ]
