# Generated by Django 2.2.6 on 2019-11-05 15:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seminars', '0028_auto_20191029_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seminar',
            name='actual_funding',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='tatsächlicher Förderbedarf'),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='actual_training_days',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='tatsächliche Bildungstage'),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='expense_accomodation',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Unterkunft'),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='expense_catering',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Verpflegung'),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='expense_referent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Referent_innen'),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seminars', to=settings.AUTH_USER_MODEL, verbose_name='Besitzer_in'),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='start_date',
            field=models.DateField(db_index=True, help_text='z.B. 2.5.2019', verbose_name='Start-Datum'),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='start_time',
            field=models.TimeField(blank=True, help_text='z.B. 15:00', null=True, verbose_name='Start-Zeit'),
        ),
    ]
