# Generated by Django 2.2.7 on 2019-11-05 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seminars', '0030_historicalfundingrate_historicalseminar_historicalseminarcomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalseminar',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='historicalseminar',
            name='updated_at',
        ),
    ]
