# Generated by Django 2.2.7 on 2019-11-05 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seminars', '0031_auto_20191105_2243'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fundingrate',
            options={'verbose_name': 'Förderungssätze', 'verbose_name_plural': 'Förderungssätze'},
        ),
        migrations.AlterModelOptions(
            name='historicalfundingrate',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Förderungssätze'},
        ),
        migrations.RemoveField(
            model_name='historicalseminarcomment',
            name='updated_at',
        ),
    ]
