# Generated by Django 2.2.7 on 2019-11-11 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminars', '0032_auto_20191106_0017'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalseminar',
            name='confirmed_at',
            field=models.DateTimeField(null=True, verbose_name='Zugesagt am'),
        ),
        migrations.AddField(
            model_name='seminar',
            name='confirmed_at',
            field=models.DateTimeField(null=True, verbose_name='Zugesagt am'),
        ),
    ]
