# Generated by Django 2.2.7 on 2019-11-17 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminars', '0033_auto_20191112_0038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalfundingrate',
            name='history_change_reason',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='historicalseminar',
            name='history_change_reason',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='historicalseminarcomment',
            name='history_change_reason',
            field=models.TextField(null=True),
        ),
    ]
