# Generated by Django 2.2.11 on 2020-03-11 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seminars', '0036_auto_20200304_2027'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fundingrate',
            options={'verbose_name': 'Förderungssatz', 'verbose_name_plural': 'Förderungssätze'},
        ),
        migrations.AlterModelOptions(
            name='historicalfundingrate',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Förderungssatz'},
        ),
    ]
