# Generated by Django 2.2.11 on 2020-05-05 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminars', '0039_seminarcheck_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalseminar',
            name='districts',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Anzahl Landkreise aus denen die Teilnehmenden kommen', null=True, verbose_name='Anzahl Landkreise'),
        ),
        migrations.AddField(
            model_name='seminar',
            name='districts',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Anzahl Landkreise aus denen die Teilnehmenden kommen', null=True, verbose_name='Anzahl Landkreise'),
        ),
    ]
