# Generated by Django 2.0.4 on 2018-07-03 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JANUNGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'JANUN-Gruppe',
                'verbose_name_plural': 'JANUN-Gruppen',
                'ordering': ['name'],
            },
        ),
    ]
