# Generated by Django 2.0.4 on 2018-07-09 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='janungroup',
            options={'ordering': ['name'], 'permissions': (('detail_janungroup', 'Kann Gruppendaten sehen'), ('can_see_all_janungroups', 'Kann alle Gruppen sehen')), 'verbose_name': 'JANUN-Gruppe', 'verbose_name_plural': 'JANUN-Gruppen'},
        ),
        migrations.AddField(
            model_name='janungroup',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='group_logos/', verbose_name='Logo'),
        ),
    ]
