# Generated by Django 2.0.4 on 2018-07-09 13:14

from django.db import migrations, models
import groups.models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_auto_20180709_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='janungroup',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=groups.models.logo_filename, verbose_name='Logo'),
        ),
    ]
