# Generated by Django 2.1.1 on 2018-09-12 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_auto_20180709_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='janungroup',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Kontakt E-Mail'),
        ),
        migrations.AddField(
            model_name='janungroup',
            name='homepage',
            field=models.URLField(blank=True, null=True, verbose_name='Homepage'),
        ),
    ]
