# Generated by Django 2.1.1 on 2018-10-26 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0007_auto_20180913_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='janungroup',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-Mail-Adresse'),
        ),
    ]
