# Generated by Django 2.0.4 on 2018-07-04 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('TEAMER', 'Teamer'), ('PRUEFER', 'Prüfer'), ('VERWALTER', 'Verwalter')], default='TEAMER', max_length=100, verbose_name='Rolle'),
        ),
    ]
