# Generated by Django 2.0.4 on 2018-07-09 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20180705_1713'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': (('detail_user', 'Kann Benutzerdaten sehen'), ('can_see_all_users', 'Kann alle Benutzer sehen'))},
        ),
    ]
