# Generated by Django 2.0.4 on 2018-07-24 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('TEAMER', 'Teamer_in'), ('PRUEFER', 'Prüfer_in'), ('VERWALTER', 'Verwalter_in')], default='TEAMER', max_length=100, verbose_name='Rolle'),
        ),
    ]
