# Generated by Django 2.1.1 on 2018-09-28 12:49

from django.db import migrations, models
import django.utils.timezone
import janun_seminarverwaltung.users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20180724_1447'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': (('detail_user', 'Kann Benutzerdaten sehen'), ('can_see_all_users', 'Kann alle Benutzer sehen')), 'verbose_name': 'Benutzer_in', 'verbose_name_plural': 'Benutzer_innen'},
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', janun_seminarverwaltung.users.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='beigetreten'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(help_text='Wichtig für Kontakt. Kann auch zum Anmelden verwendet werden', max_length=254, unique=True, verbose_name='E-Mail-Adresse'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='aktiv'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='Admin-Zugang'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Voller Name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, help_text='Optional. Kann auch zum Anmelden verwendet werden', max_length=40, unique=True, verbose_name='Benutzername'),
        ),
    ]
