# Generated by Django 2.1.1 on 2018-10-15 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20180928_1449'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': (('detail_user', 'Kann Benutzerdaten sehen'), ('see_all_users', 'Kann alle Benutzer sehen')), 'verbose_name': 'Benutzer_in', 'verbose_name_plural': 'Benutzer_innen'},
        ),
    ]
