# Generated by Django 2.1.1 on 2018-10-18 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20181015_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reviewed',
            field=models.BooleanField(default=False, help_text='Darf erst auf Gruppendaten zugreifen, wenn überprüft.', verbose_name='überprüft'),
        ),
    ]
