# Generated by Django 2.1.1 on 2018-10-18 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_reviewed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='reviewed',
            new_name='is_reviewed',
        ),
    ]
