# Generated by Django 2.1.1 on 2018-10-19 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20181018_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='group_hats',
            field=models.ManyToManyField(blank=True, related_name='group_hats', to='groups.JANUNGroup', verbose_name='Gruppenhüte'),
        ),
        migrations.AlterField(
            model_name='user',
            name='janun_groups',
            field=models.ManyToManyField(blank=True, related_name='members', to='groups.JANUNGroup', verbose_name='Gruppe(n)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Voller Name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, help_text='Muss nicht gesetzt sein, da auch die E-Mail-Adresse zum Login genutzt werden kann.', max_length=40, null='True', verbose_name='Benutzername'),
        ),
    ]
