# Generated by Django 2.1.1 on 2018-10-26 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20181019_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='janun_groups',
            field=models.ManyToManyField(blank=True, related_name='members', to='groups.JANUNGroup', verbose_name='Gruppen-Mitgliedschaften'),
        ),
    ]
