# Generated by Django 2.1.1 on 2018-12-07 17:03

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20181122_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='group_hats',
            field=models.ManyToManyField(blank=True, help_text='Für mehrere, drücke <kbd>Strg</kbd>.', related_name='group_hats', to='groups.JANUNGroup', verbose_name='Gruppenhüte'),
        ),
        migrations.AlterField(
            model_name='user',
            name='janun_groups',
            field=models.ManyToManyField(blank=True, help_text='Für mehrere, drücke <kbd>Strg</kbd>.', related_name='members', to='groups.JANUNGroup', verbose_name='Gruppen-Mitgliedschaften'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Damit wir Rückfragen zu Deinem Seminar zeitnah mit Dir klären können.', max_length=128, verbose_name='Telefonnummer'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=40, null='True', verbose_name='Benutzername'),
        ),
    ]
