# Generated by Django 2.2.4 on 2019-09-07 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('name',), 'verbose_name': 'Konto', 'verbose_name_plural': 'Konten'},
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_visit',
        ),
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.TextField(blank=True, verbose_name='Post-Adresse'),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am'),
        ),
        migrations.AlterField(
            model_name='user',
            name='group_hats',
            field=models.ManyToManyField(blank=True, related_name='group_hats', to='groups.JANUNGroup', verbose_name='Gruppenhüte'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_reviewed',
            field=models.BooleanField(default=False, verbose_name='überprüft?'),
        ),
        migrations.AlterField(
            model_name='user',
            name='janun_groups',
            field=models.ManyToManyField(blank=True, related_name='members', to='groups.JANUNGroup', verbose_name='JANUN-Gruppen'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Teamer_in', 'Teamer_in'), ('Prüfer_in', 'Prüfer_in'), ('Verwalter_in', 'Verwalter_in')], default='Teamer_in', max_length=255, verbose_name='Rolle'),
        ),
        migrations.AlterField(
            model_name='user',
            name='telephone',
            field=models.CharField(blank=True, max_length=100, verbose_name='Telefon-Nummer'),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Geändert am'),
        ),
    ]
