# Generated by Django 2.2.5 on 2019-09-11 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190907_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_visit',
            field=models.DateTimeField(null=True, verbose_name='Letzter Besuch'),
        ),
    ]
