# Generated by Django 2.2.5 on 2019-09-13 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_last_visit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_reviewed',
            field=models.BooleanField(default=False, verbose_name='überprüft'),
        ),
    ]
