# Generated by Django 2.2.6 on 2019-10-15 20:00

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20190929_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='telephone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Für wichtige Rückfragen zu Seminaren', max_length=128, region=None, verbose_name='Telefonnummer'),
        ),
    ]
