# Generated by Django 2.2.6 on 2019-10-15 20:43

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20191015_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='telephone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, error_messages={'invalid': 'Bitte gültige Telefonnummer eingeben, z.B. 0511 1241512'}, max_length=128, region=None, verbose_name='Telefonnummer'),
        ),
    ]
