# Generated by Django 2.2.6 on 2019-10-19 22:26

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0002_auto_20181220_0803'),
        ('users', '0007_auto_20191015_2243'),
    ]

    operations = [
        migrations.CreateModel(
            name='JANUNSeminarPreferences',
            fields=[
                ('preferences_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='preferences.Preferences')),
                ('help_phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Hilfe-Telefon')),
                ('help_email', models.EmailField(max_length=254, verbose_name='Hilfe-E-Mail')),
                ('seminar_policy_url', models.URLField(verbose_name='Link Seminarrichtlinie')),
                ('data_protection_policy_url', models.URLField(verbose_name='Link Datenschutzrichtlinie')),
            ],
            bases=('preferences.preferences',),
            managers=[
                ('singleton', django.db.models.manager.Manager()),
            ],
        ),
    ]
