# Generated by Django 2.2.6 on 2019-10-24 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_janunseminarpreferences_legal_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Voller Name'),
        ),
    ]
