# Generated by Django 2.2.7 on 2019-11-05 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_historicaljanunseminarpreferences_historicaluser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaluser',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='historicaluser',
            name='last_visit',
        ),
    ]
