# Generated by Django 2.2.7 on 2019-11-06 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20191105_2021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaluser',
            name='updated_at',
        ),
    ]
