# Generated by Django 2.2.7 on 2019-11-17 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_remove_historicaluser_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaljanunseminarpreferences',
            name='history_change_reason',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='historicaluser',
            name='history_change_reason',
            field=models.TextField(null=True),
        ),
    ]
